= AsciiDoc
Alternative to Markdown, better toolset for writing documentation
:toc:
:toc-placement!:
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]


toc::[]

[quote, https://asciidoctor.org/docs/user-manual/#asciidoc-syntax-processing]
Asciidoctor reads and parses text written in the AsciiDoc syntax, then feeds the parse tree into a set of built-in templates to produce HTML5, PDF, DocBook 5, etc.

ifdef::status[]
.*Project health*
image:https://img.shields.io/travis/asciidoctor/asciidoctor/master.svg[Build Status (Travis CI), link=https://travis-ci.org/asciidoctor/asciidoctor]
image:https://ci.appveyor.com/api/projects/status/ifplu67oxvgn6ceq/branch/master?svg=true&amp;passingText=green%20bar&amp;failingText=%23fail&amp;pendingText=building%2E%2E%2E[Build Status (AppVeyor), link=https://ci.appveyor.com/project/asciidoctor/asciidoctor]
//image:https://img.shields.io/coveralls/asciidoctor/asciidoctor/master.svg[Coverage Status, link=https://coveralls.io/r/asciidoctor/asciidoctor]
//image:https://codeclimate.com/github/asciidoctor/asciidoctor/badges/gpa.svg[Code Climate, link="https://codeclimate.com/github/asciidoctor/asciidoctor"]
image:https://inch-ci.org/github/asciidoctor/asciidoctor.svg?branch=master[Inline docs, link="https://inch-ci.org/github/asciidoctor/asciidoctor"]
endif::[]

https://asciidoctor.org/docs/user-manual/[User Manual]

* https://asciidoctor.org/docs/asciidoc-vs-markdown/#comparison-by-example
* https://asciidoctor.org/docs/user-manual/#quote
* https://asciidoctor.org/docs/user-manual/#source-code-blocks
** https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code
* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#bibliography
* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#section-footnotes


https://asciidoctor.org/docs/asciidoc-recommended-practices/
https://asciidoctor.org/docs/asciidoc-recommended-practices/#attribute-groups

https://asciidoctor.org/docs/install-asciidoctor-macos/


Diagrams
https://asciidoctor.org/docs/asciidoctor-diagram/
https://github.com/lewish/asciiflow2




https://leanpub.com/awesomeasciidoctornotebook/read#leanpub-auto-source-code

== Plugins

Visual Studio Code Extension

* https://github.com/asciidoctor/asciidoctor-vscode
** https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode

== Reviews

http://www.ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/[2016 - Why You Shouldn’t Use “Markdown” for Documentation]

https://ivoanjo.me/blog/2017/10/22/asciidoc-an-awesome-markdown-alternative/[2017 - asciidoc: an awesome markdown alternative]

== Examples

=== Source Highlighting

Basic source example with Callouts
[source, asciidoc]
----
  [source,ruby]
  ----
  require 'sinatra' // <1>

  get '/hi' do // <2>
    "Hello World!" // <3>
  end
  ----
  <1> Library import
  <2> URL mapping
  <3> HTTP response body
----

AsciiDoc source example (_*remember to indent*_)
[source,asciidoc]
----
  [source, asciidoc]
  ----
    [source,ruby]
    ----
    require 'sinatra' \<1>

    get '/hi' do \<2>
      "Hello World!" \<3>
    end
    ----
    <1> Library import
    <2> URL mapping
    <3> HTTP response body
  ----
----

=== AsciiDoc on Github
(User example hosted in Github) https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#callouts

Common Stuff I would probably do <<examples/asciidoc-example.adoc#,asciidoc-example.adoc>>