= Cypress
:toc:

https://www.cypress.io[Home]
https://github.com/cypress-io/cypress[Repo]
https://docs.cypress.io/api/api/table-of-contents.html[API Docs]
https://docs.cypress.io/examples/examples/recipes.html#Fundamentals[Recipes]
https://docs.cypress.io/plugins/#authentication[Plugins]

== Install

`npm install cypress --save-dev`
`yarn add cypress --dev`

== Setup

https://docs.cypress.io/guides/tooling/intelligent-code-completion.html#Set-up-in-your-Dev-Environment

Reference type declarations via `jsconfig`

.jsconfig.json
[source,json]
----
{
  "include": [
    "./node_modules/cypress",
    "cypress/**/*.js"
  ]
}
----

Enable Configuration Tooltips for vscode

.cypress.json
[source,json]
----
{
    "$schema": "https://on.cypress.io/cypress.schema.json"
}
----

Ignore

.gitignore
[source]
----
# Logs
logs
*.log

# Runtime data
pids
*.pid
*.seed

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# node-waf configuration
.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)
build/Release

# Dependency directory
# https://www.npmjs.org/doc/misc/npm-faq.html#should-i-check-my-node_modules-folder-into-git
node_modules
cypress/videos
cypress/screenshots
----

== Run

Launch Cypress Test Runner
`npx cypress open`
`yarn run cypress open`

https://docs.cypress.io/guides/guides/command-line.html#Commands[Running from CLI]
`cypress run --env host=api.dev.local --spec 'cypress/integration/admin/**/*'`


== Folder Structure

[source]
----
├── cypress
│   ├── fixtures <1>
│   │   └── example.json 
│   ├── integration
│   │   └── examples
│   ├── plugins
│   │   └── index.js <4>
│   └── support
│       ├── commands.js
│       └── index.js
├── cypress.json <3>
├── jsconfig.json <2>
├── package-lock.json
└── package.json
----
<1> Use this to store/load data using `cy.fixture` <<Fixtures>>
<2> Reference type declarations for project https://docs.cypress.io/guides/tooling/intelligent-code-completion.html#Reference-type-declarations-via-jsconfig[(see)]
<3> Default Cypress configuration file https://docs.cypress.io/guides/references/configuration.html#Options[(see)]
<4> Aside from plugins, can be used to load custom configuration file on startup

== Environment Variables (ENV)

Accessed in test by using `Cypress.env("variable_name")`

Can be passed into Cypress in a few ways...

- Command Line session
```
$ VAR=foo
$ export VAR=bar
```

- Passed in via Cypress CLI
`cypress run --env VAR=foo ...`

- ENV defined in the file cypress.json
```
{
  "env": {
    "my-var": "ok"
  },
  
  ...
}
```

- Set some from the https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/server-communication__env-variables[/plugins/index.js]
```
module.exports = (on, config) => {
  // we can grab some process environment variables
  // and stick it into config.env before returning the updated config
  config.env = config.env || {}
  // you could extract only specific variables
  // and rename them if necessary
  config.env.FOO = process.env.FOO
  config.env.BAR = process.env.BAR
  console.log('extended config.env with process.env.{FOO, BAR}')
  return config
}
```


== Fixtures

https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__fixtures

`cy.fixture`

https://youtu.be/cVNE-Q4rzWY?t=210
`cy.route('GET', '/api/todos', 'fixture:todo')`


== Configuration File

https://docs.cypress.io/guides/references/configuration.html#Options

=== Support for host mapping

https://github.com/cypress-io/cypress-example-recipes/blob/b536a6b505b574aa3c9bde12d0138459f31a9d2b/examples/logging-in__single-sign-on/cypress/integration/logging-in-single-sign-on-spec.js#L20

== Issues

https://github.com/cypress-io/cypress/issues/3221#issuecomment-498274788[cy.request doesn't set cookie with specific domain]