=== Conditional and Loop Statements

// tag::python[]
ifdef::python,showall[]

```
for item in list:
    print item

while (total < max_val):
    total += values[i]
    i += 2
```
endif::[]
// end::python[]


// tag::javascript[]
ifdef::javascript,showall[]

If you take the above into account, you can iterate over an array using the following:

```
for (var i = 0; i < a.length; i++) {
 // Do something with a[i]
}
```

This is slightly inefficient as you are looking up the length property once every loop. An improvement is this:

```
for (var i = 0, len = a.length; i < len; i++) {
 // Do something with a[i]
}
```

An even nicer idiom is:

```
for (var i = 0, item; item = a[i++];) {
 // Do something with item
}
```

Here we are setting up two variables. The assignment in the middle part of the for loop is also tested for truthfulness — if it succeeds, the loop continues. Since i is incremented each time, items from the array will be assigned to item in sequential order. The loop stops when a "falsy" item is found (such as undefined).
Note that this trick should only be used for arrays which you know do not contain "falsy" values (arrays of objects or DOM nodes for example). If you are iterating over numeric data that might include a 0 or string data that might include the empty string you should use the i, len idiom instead. footnote:[https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript]

endif::[]
// end::javascript[]